/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interactions */
        get: operations["list_interactions_api_interactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interactions/{interaction_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Interaction
         * @description Resolve an interaction; the first answer wins (409 afterwards).
         */
        post: operations["answer_interaction_api_interactions__interaction_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /**
         * Launch Session
         * @description Launch a new agent run through a control-capable adapter.
         */
        post: operations["launch_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Events */
        get: operations["session_events_api_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prompt Session */
        post: operations["prompt_session_api_sessions__session_id__prompt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Terminate Session */
        post: operations["terminate_session_api_sessions__session_id__terminate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Answer
         * @description A human's resolution of an interaction.
         *
         *     Permissions use ``decision`` (optionally with ``updated_input`` to run the
         *     tool with edited arguments); questions use ``text``. For a denied
         *     permission, ``text`` carries the reason shown to the agent.
         */
        Answer: {
            /** Decision */
            decision?: ("allow" | "deny") | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Updated Input */
            updated_input?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AnswerRequest
         * @description A human's answer: ``decision`` for permissions, ``text`` for questions
         *     (or the deny reason).
         */
        AnswerRequest: {
            /** Decision */
            decision?: ("allow" | "deny") | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Updated Input */
            updated_input?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Event
         * @description Immutable envelope for a single event.
         *
         *     ``id`` is a ULID, so lexicographic order is chronological order - clients
         *     use it as a cursor when reconciling after a disconnect.
         */
        Event: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Id */
            id?: string;
            /**
             * Node
             * @default local
             */
            node: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Session Id */
            session_id?: string | null;
            /**
             * Source
             * @default core
             */
            source: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Type */
            type: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** EventListResponse */
        EventListResponse: {
            /** Cursor */
            cursor: string | null;
            /** Events */
            events: components["schemas"]["Event"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Node */
            node: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * Interaction
         * @description The canonical record of one interaction (mutable, like Session).
         */
        Interaction: {
            /** Adapter */
            adapter: string;
            answer?: components["schemas"]["Answer"] | null;
            /** Answered At */
            answered_at?: string | null;
            /**
             * Answered By
             * @default
             */
            answered_by: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Id */
            id: string;
            kind: components["schemas"]["InteractionKind"];
            /** Native Id */
            native_id: string;
            /** Options */
            options?: string[];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Session Id */
            session_id: string;
            /** @default pending */
            status: components["schemas"]["InteractionStatus"];
            /** Timeout At */
            timeout_at?: string | null;
            /** Title */
            title: string;
        };
        /**
         * InteractionKind
         * @enum {string}
         */
        InteractionKind: "permission" | "question";
        /** InteractionListResponse */
        InteractionListResponse: {
            /** Interactions */
            interactions: components["schemas"]["Interaction"][];
            /** Pending */
            pending: number;
        };
        /**
         * InteractionStatus
         * @enum {string}
         */
        InteractionStatus: "pending" | "answered" | "timed_out" | "cancelled";
        /** LaunchRequest */
        LaunchRequest: {
            /** Adapter */
            adapter: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            /**
             * Permission Mode
             * @default
             */
            permission_mode: string;
            /**
             * Project
             * @default
             */
            project: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
        };
        /** PromptRequest */
        PromptRequest: {
            /** Prompt */
            prompt: string;
        };
        /**
         * Session
         * @description The registry's canonical record of one agent session.
         */
        Session: {
            /** Adapter */
            adapter: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Ended At */
            ended_at?: string | null;
            /** Id */
            id: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Model */
            model?: string | null;
            /** Native Id */
            native_id: string;
            /**
             * Project
             * @default
             */
            project: string;
            /** @default discovered */
            state: components["schemas"]["SessionState"];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["Session"][];
        };
        /**
         * SessionState
         * @enum {string}
         */
        SessionState: "discovered" | "starting" | "running" | "waiting_on_user" | "completed" | "failed" | "stopped" | "archived";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_events_get: {
        parameters: {
            query?: {
                after?: string | null;
                /** @description exclusive cursor for paging backward */
                before?: string | null;
                /** @description event type pattern: exact, `ns.*`, or `*` */
                type?: string;
                session?: string | null;
                limit?: number;
                /** @description `desc` = newest first */
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_interactions_api_interactions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["InteractionStatus"] | null;
                session?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_interaction_api_interactions__interaction_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    launch_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_events_api_sessions__session_id__events_get: {
        parameters: {
            query?: {
                after?: string | null;
                type?: string;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prompt_session_api_sessions__session_id__prompt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    terminate_session_api_sessions__session_id__terminate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
