// Convenience aliases over the OpenAPI-generated schema (src/api/schema.d.ts,
// regenerated by `npm run generate` from the server's exported openapi.json).
import type { components } from "./schema";

export type Session = components["schemas"]["Session"];
export type ProdeoEvent = components["schemas"]["Event"];
export type SessionState = Session["state"];
export type Interaction = components["schemas"]["Interaction"];
export type AnswerRequest = components["schemas"]["AnswerRequest"];
export type LaunchRequest = components["schemas"]["LaunchRequest"];

export const ACTIVE_STATES: readonly string[] = [
  "running",
  "waiting_on_user",
  "starting",
  "discovered",
];

export function isActive(state: string): boolean {
  return ACTIVE_STATES.includes(state);
}
